## End point(s) relative URLs
encryptionPath=v1/identity/encrypt?isInternal=false
internalEncryptionPath=v1/identity/encrypt?isInternal=true
encodePath=v1/identity/encode
decodePath=v1/identity/decode
decryptPath=/idauthentication/v1/internal/decrypt
encodeFilePath=v1/identity/encodeFile
decodeFilePath=v1/identity/decodeFile/?fileName=cbeff
validateSignaturePath=v1/identity/validateSign?signature=$signature$
splitEncryptedData=v1/identity/splitEncryptedData
masterSchemaURL=/v1/masterdata/idschema/latest
fetchLocationData=/v1/masterdata/locations/all?pageNumber=0&pageSize=1000&sortBy=createdDateTime&orderBy=desc
fetchTitle=/v1/masterdata/title
fetchZoneCode=/v1/masterdata/zones/hierarchy/
fetchZone=/v1/masterdata/zones/zonename
fetchLocationHierarchyLevels=/v1/masterdata/locationHierarchyLevels/
fetchLocationHierarchy=/v1/masterdata/locations/locationhierarchy/
leafZoneUrl=/v1/masterdata/zones/leafzones/

## Check are we using these properties. If not remove them
zoneCode_to_beMapped=NTH