-- --------------------------------------------------------------------------------------------------------
-- Database Name: mosip_master
-- Release Version 	: 1.2.1
-- Purpose    		: Revoking Database Alter deployement done for release in Master DB.       
-- Create By   		: Balaji A
-- Created Date		: April 2023
-- 
-- Modified Date        Modified By         Comments / Remarks
-- -----------------------------------------------------------------------------------------------------------

-- -----------------------------------------------------------------------------------------------------------
