FetchAppConfig:
   MasterData_FetchAppConfig_allValid_smoke:
      endPoint: /v1/masterdata/configs
      uniqueIdentifier: TC_Masterdata_FetchAppConfig_01
      description: Verify that the system successfully fetches application configuration records with valid input data
      role: admin
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: masterdata/FetchAppConfig/fetchAppConfig
      outputTemplate: masterdata/FetchAppConfig/fetchAppConfigResult
      input: '{
}'
      output: '{
}'