GetPossiableValues:
   Admin_GetPossiableValues_allValid_smoke:
      endPoint: /v1/masterdata/possiblevalues/{fieldName}?langCode=eng
      uniqueIdentifier: TC_Masterdata_GetPossiableValues_01
      description: Verify that the system successfully returns all possible values when a valid request is made (smoke test)
      role: admin
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: masterdata/GetPossiableValues/getPossiableValues
      outputTemplate: masterdata/GetPossiableValues/getPossiableValuesResult
      input: '{
  "fieldName":"bloodType"
}'
      output: '{
"eng": [{
       "dataType": "string"
		}]
}'

   Admin_GetPossiableValues_Invalid_Invalid_FieldName:
      endPoint: /v1/masterdata/possiblevalues/{fieldName}?langCode=eng
      uniqueIdentifier: TC_Masterdata_GetPossiableValues_02
      description: Verify that the system returns an error or handles gracefully when an invalid field name is provided while fetching possible values
      role: admin
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: masterdata/GetPossiableValues/getPossiableValues
      outputTemplate: masterdata/error
      input: '{
  "fieldName":"abc"
}'
      output: '{
}'  

   Admin_GetPossiableValues_Invalid_Invalid_langCode:
      endPoint: /v1/masterdata/possiblevalues/{fieldName}?langCode=abc
      uniqueIdentifier: TC_Masterdata_GetPossiableValues_03
      description: Verify that the system returns an error or handles gracefully when an invalid language code is provided while fetching possible values
      role: admin
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: masterdata/GetPossiableValues/getPossiableValues
      outputTemplate: masterdata/error
      input: '{
  "fieldName":"bloodType"
}'
      output: '{
}'