\c :mosipdbname

GRANT CONNECT
   ON DATABASE mosip_master
   TO :dbuname;

GRANT USAGE
   ON SCHEMA master
   TO :dbuname;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
      ON ALL TABLES IN SCHEMA master
          TO :dbuname;

ALTER DEFAULT PRIVILEGES IN SCHEMA master
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO :dbuname;

