GetCredentialTypes:
   Master_GetApplicationConfigs_smoke:
      endPoint: /v1/masterdata/applicationconfigs
      role: admin
      description: Retrieve Application Configs by all valid data.
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: masterdata/GetApplicationConfigs/getApplicationConfigs
      outputTemplate: masterdata/GetApplicationConfigs/getApplicationConfigsResult
      input: '{
      }'
      output: '{
          "primaryLangCode": "$IGNORE$",
		  "secondaryLangCode": "$IGNORE$",
		  "version": "$IGNORE$"
      }'