apiVersion: v2
name: masterdata
description: A Helm chart for MOSIP Masterdata module
type: application
version: 12.1.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - masterdata
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
