CreateApplicationType:
   Masterdata_CreateApplicationType_All_Valid_Smoke:
      endPoint: /v1/masterdata/applicationtypes
      role: admin
      templateFields: ["langCode"]
      description: Create application type with valid data
      restMethod: post
      inputTemplate: masterdata/CreateApplicationType/createApplicationType
      outputTemplate: masterdata/CreateApplicationType/createApplicationTypeResult
      input: '{
    "description": "test",
	"name": "test",
	"langCode": "eng",
	"code": "dumbo",
	"requesttime": "$TIMESTAMP$"
}'
      output: '{
	"code": "dumbo"
}'
