name: Maven Package upon a push

on:
  push:
    branches:
      - master
      - 1.*
      - develop  
  
jobs:
  build-maven-admin:
    uses: syedsalman3753/kattu/.github/workflows/maven-build.yml@master
    with:
      WORKDIR: ./admin
      SERVICE_NAME: admin

  publish_to_nexus_admin:
    needs: build-maven-admin
    uses: syedsalman3753/kattu/.github/workflows/publish-to-nexus.yml@master
    with:
      WORKDIR: ./admin
    secrets:
      OSSRH_USER: mosip
      OSSRH_SECRET: mosip@123
      OSSRH_URL: https://oss.sonatype.org/service/local/staging/deploy/maven2
      OSSRH_TOKEN: 'xxxxx'
      GPG_SECRET: 'xxxx'

  build_dockers:
    needs: build-maven-admin
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'admin/admin-service'
            SERVICE_NAME: 'admin-service'
            JAR_ZIP_NAME: 'admin'
          - SERVICE_LOCATION: 'admin/kernel-masterdata-service'
            SERVICE_NAME: 'kernel-masterdata-service'
            JAR_ZIP_NAME: 'admin'
          - SERVICE_LOCATION: 'admin/kernel-syncdata-service'
            SERVICE_NAME: 'kernel-syncdata-service'
            JAR_ZIP_NAME: 'admin'
    uses: syedsalman3753/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      JAR_ZIP: ${{ matrix.JAR_ZIP_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}

  sonar_analysis:
    #needs: build-maven-admin
    uses: syedsalman3753/kattu/.github/workflows/maven-sonar-analysis.yml@master
    with:
      SERVICE_LOCATION: ./admin
    secrets:
      #GITHUB_TOKEN: 'xxxx'
      SONAR_TOKEN: 'xxxx'
      ORG_KEY: 'xxxx'