
name: Maven Package upon a push 

on:
  push:
    branches:
      - master
      - 1.*
      - develop  
  
jobs:
  build-maven-admin:
    uses: syedsalman3753/kattu/.github/workflows/maven-build.yml@master
    with:
      workdir: ./admin
      service_name: admin

  publish_to_nexus_admin:
    needs: build-maven-admin
    uses: syedsalman3753/kattu/.github/workflows/publish_to_nexus.yml@master
    with:
      workdir: ./admin
      service_name: admin
    secrets:
      ossrh_user: mosip
      ossrh_secret: mosip@123
      ossrh_url: https://oss.sonatype.org/service/local/staging/deploy/maven2
      ossrh_token: 'xxxxx'

  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'admin/admin-service'
            SERVICE_NAME: 'admin-service' 'kernel-masterdata-service', 'kernel-syncdata-service']
            JAR_ZIP_NAME: 'admin'
          - SERVICE_LOCATION: 'admin/kernel-masterdata-service' 'admin/kernel-syncdata-service']
            SERVICE_NAME: 'kernel-masterdata-service', 'kernel-syncdata-service']
            JAR_ZIP_NAME: 'admin'
          - SERVICE_LOCATION: 'admin/kernel-syncdata-service'
            SERVICE_NAME: 'kernel-syncdata-service'
            JAR_ZIP_NAME: 'admin'
    uses: syedsalman3753/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      JAR_ZIP: ${{ matrix.JAR_ZIP }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
