name: Trivy Scan

on:
  push:
    branches:
      - main
      - 'release-1*'
      - develop
      - '1.2.*'
      - master
      - MOSIP-35889
  pull_request:
    branches:
      - main
      - 'release-1*'
      - develop
      - '1.2.*'
      - master
      - MOSIP-35889

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.dev_namespace_docker_hub }}
      SERVICE_NAME: admin-services
      VERSION: latest  # Modify this as needed or set dynamically based on your versioning scheme

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd admin/admin-service
          docker build . --file Dockerfile --tag ${{ env.SERVICE_NAME }}:${{ env.VERSION }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{ env.SERVICE_NAME }}:${{ env.VERSION }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
